### ISSUE TITLE
KeyError: 'storageunit_id' when applying LOPF with storages

### ISSUE THREAD

**Issue by simnh** [openego/ego.io#12]
So I am working on features/clustering branch, where the latest dev commit is merge as well. I added storages to my scenario and I get the following error:

```
ing of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/uni/repos/eGo/ego.powerflow/egopowerflow/examples/hv_grid_lopf.py", line 45, in <module>
    components = import_components(tables, session, scenario)
  File "/home/simon/uni/repos/eGo/ego.powerflow/egopowerflow/tools/io.py", line 224, in import_components
    index_col=id_col)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/sql.py", line 331, in read_sql_query
    parse_dates=parse_dates, chunksize=chunksize)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/sql.py", line 1096, in read_query
    parse_dates=parse_dates)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/sql.py", line 161, in _wrap_result
    frame.set_index(index_col, inplace=True)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2917, in set_index
    level = frame[col]._values
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 3541, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4443)
  File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4289)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13733)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13687)
KeyError: 'storageunit_id'
```

I think the problem here might be the following: 

Isinde the function 'import components' in the `io.py` file `table.__name__` is used to do some stuff, this works for all components where the table name is the same as the class name. In the case of the Storage, the class is called `StorageUnit`, the ` __tablename__`  is indeed defined as `storage` but as the function (import_components) is using `__name__` it yields `storageunit`. Should that be `__tablename__` everywhere there? 

Can somebody follow me? this may be linked to #8 but I am not sure...

**Comment by simnh** [comment]
Ok, sorry, I just realised that this should maybe go to ego.powerflow. This repo-structure is really confusing to me... I created a pull request inside the other repository, as I fixed the error for me. But of course there might be some things I did not have in mind (that are affected as well)

See:
https://github.com/openego/ego.powerflow/pull/18

**Comment by gplssm** [comment]
True, structure is currently confusing... Hopefully, we get to work on this soon. I'll be back to this project from march again.

_ego.powerflow_ has currently 3 tasks
1. To run PF calculation with osmTGmod model
2. Run the LOPF example
3. Is used by dingo to run 2 worst-case PFs

If you want to change something have these three tasks in mind. @ulfmueller and @nesnoj can give you support on that.

**Comment by simnh** [comment]
Ok, but are there any test? How do pulls work? Can somebody check if 1, (2) ,3 work with the pull  openego/ego.powerflow#18 (I guess two should work, as I build upon that with my stuff)?

**Comment by nesnoj** [comment]
Can we close this one? @gplssm

**Comment by gplssm** [comment]
Yes, from my side

**Comment by nesnoj** [comment]
Ok @simnh ?
